# This file is created automatically by `pak:::proj_create()`
# Please do not edit this file
{
    cat("-> Setting up private project library.\n")
    .libPaths(unique(c(file.path("r-packages", R.version$platform, 
        getRversion()[, 1:2]), .libPaths())))
    if (file.exists("~/.Rprofile")) 
        source("~/.Rprofile")
    if (interactive()) {
        cat("-> Call `pak:::proj_install_dev()` to install/update dependencies.\n")
        cat("-> Call `pak:::proj_load()` to load the package.\n")
    }
}
