CC = `"$(R_HOME)/bin/R" CMD config CC`
CFLAGS = `"$(R_HOME)/bin/R" CMD config CFLAGS`

supervisor.exe: supervisor.c
	$(CC) $(CFLAGS) supervisor.c -o supervisor.exe

all: supervisor

clean:
	rm -f supervisor.exe
