CC = `"$(R_HOME)/bin/R" CMD config CC`
CFLAGS = `"$(R_HOME)/bin/R" CMD config CFLAGS`

supervisor.exe: supervisor.c
	$(CC) $(CFLAGS) supervisor.c -o supervisor.exe

all: supervisor.exe

clean:
	rm -f supervisor supervisor.dSYM supervisor.exe
